logging:
  level: INFO
  loggers:
    com.app.whse: DEBUG
  appenders:
    - type: console
      threshold: INFO
      logFormat: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    - type: file
      currentLogFilename: file.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: /var/log/myapp-%d.log.gz
      archivedFileCount: 5
      logFormat: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

    
 cache:
  maximumSize: 1000
  expireAfterWrite: 10m
